version: '3.5'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: FleetControl
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: ./fleet-control-api
      dockerfile: Dockerfile
    env_file:
      - ./fleet-control-api/.env
    container_name: fleet-control-api
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./Fleet-Control-main
      dockerfile: Dockerfile
    container_name: fleet-control-frontend
    depends_on:
      - api
      - postgres
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
   
    depends_on:
      - frontend
      - api
      - postgres
volumes:
  postgres-data: